export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="nick-modified"

ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(node npm yarn history zsh-syntax-highlighting)

# brew tab completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi
# npm tab completion
. <(npm completion)

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# Load direnv
eval "$(direnv hook bash)"

for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

source $ZSH/oh-my-zsh.sh
